config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#toppage"
  get "/search", :to => "users#search" 
  resources :rules, only: [:index]
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  } 
  devise_scope :user do
    get "users/sign_in", :to => "users/sessions#new"
    get "/users/sign_out", :to => "users/sessions#destroy" 
    get 'password_edit' => 'users/registrations#password_edit'
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :posts do 
    member do 
      post "add", to: "favorites#create"
    end
    resources :comments
  end
  
  resources :favorites, only: [:destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image,:description,presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments
  has_many :favorites
  has_many :users, through: :favorites
  has_many :notifications, dependent: :destroy
  
  def create_notification_favorite!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @posts = Post.where(user_id: current_user.following).order("created_at DESC").page(params[:page]).per(10)
    @comment = Comment.new
  end
  
  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id if user_signed_in?
    if @post.save
      redirect_to post_path @post
      flash[:notice] = "投稿に成功しました"
    else
      render :new
      flash[:danger] = "投稿に失敗しました"
    end
  end
    
  def new
    @post = Post.new
  end
    
  def show
    @post = Post.find(params[:id])
    @user = User.find_by(id: @post.user_id)
    @comment  =  @post.comments.build
    @comments =  Comment.where(post_id: @post.id).order("created_at DESC")
  end
    
  private
      
    def post_params
      params.require(:post).permit(:image, :description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="container">
  <div class="row mt-5 mb-5">
    <div class="col-md-8">
      <% @posts.each do |post| %>
        <div class="follwing-posts mb-5">
          <div class="post-user">
            <%= link_to image_tag(post.user.image.thumb.url,class:"profile-pic mr-2"), user_path(post.user) %>
            <strong><%= post.user.username %> </strong>
          </div>
          <button type="button" data-toggle="modal" data-target=".bd-example-modal-lg-<%= post.id%>">
            <%= image_tag(post.image.url,class: "img img-fluid", :size =>'620x400') unless post.image.blank? %>
          </button>
          <div class="post-details">
            <div class="post-actions">
              <%= link_to add_post_path(post), method: :post do %>
                <i class="fa fa-heart fa-2x post-like"></i>
              <% end %>
              <%= link_to post_path(post) do %>
                <i class="fa fa-comment fa-2x post-comments"></i>
              <% end %>
            </div>
            <strong><%= link_to post.user.username,user_path(post.user) %> </strong>
            <%= post.description unless post.description.blank? %>
            
            <div class="comments-list mt-3">
              <% post.comments.each do |comment| %>
                <div class="coment-content">
                  <strong><%=link_to comment.user.username, user_path(comment.user) %></strong>
                  <%=comment.content %>
                </div>
                     
                <!--modal-->
                <div class="modal fade bd-example-modal-lg-<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content p-3">
                      <div class="post-user">
                        <%= link_to image_tag(post.user.image.thumb.url,class:"profile-pic mr-2"), user_path(post.user) %>
                        <strong><%= post.user.username %> </strong>
                      </div>
                      <%= image_tag(post.image.url,class: "img img-fluid", :size =>'800x350') unless post.image.blank? %>
                      <div class="modal-comments p-3">
                        <% post.comments.each do |comment| %>
                          <div class="coment-content mb-2">
                            <%= link_to image_tag(comment.user.image.thumb.url,class:"profile-pic mr-2"), user_path(post.user) %>
                            <strong><%=link_to comment.user.username, user_path(comment.user) %></strong>
                            <%=comment.content %>
                          </div>
                        <% end %>
                      </div>
                    </div><!--modal-content-->
                  </div><!--modal-dialog modal-lg-->
                </div><!--modal fade bd-example-modal-lg-->
              <% end %><!--post.comments.each do |comment|-->
            </div>
            <p class="text-muted time-ago mt-3"><%= time_ago_in_words post.created_at %>前に作成</p>
          </div>
          
          <div class="comment-box">
            <%= form_for [post, @comment] do |f| %>
              <div class="input-group">
                <%= f.text_field :content, placeholder: "コメントを入力してください....", class: "form-control post-comment" %>
                <%= f.submit "コメントする", class: "btn btn-success" %>
              </div>
            <% end %><!--form_for [post, @comment] do |f|-->
          </div>
          
        </div>
      <% end %><!--@posts.each do |post|-->
      <%= paginate @posts %>
    </div><!--col-md-8-->
    
    <div class="col-md-4">
      <p><strong><%= link_to image_tag(current_user.image.thumb.url, class:"img-border"), user_path(current_user.id) if current_user.image.present? %>
      <%= current_user.username %></strong></p>
    </div><!--col-md-4-->
  
  </div><!--row-->
</div>

app/views/posts/new.html.erb
<% provide(:title, "post") %>
<div class="form-style">
  <h2>新規投稿</h2>
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :投稿画像 %>
      <%= f.file_field :image, class: "form-control" %>    
    </div>
    
    <div class="form-group">
      <%= f.label :投稿内容 %>
      <%= f.text_area :description, class: "form-control" %>    
    </div>
    
    <%= f.submit "投稿する", class: "btn btn-success"%>
    
  <% end %>
</div>

app/views/posts/show.html.erb
<% provide(:title, "photo") %>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8">
      
      <div class="post-user">
        <%= link_to image_tag(@user.image.thumb.url,class:"profile-pic mr-2"), "#" %>
        <strong><%= @user.username %> </strong>
      </div>
      <div class="show-image">
        <%= image_tag(@post.image.url,class: "img img-fluid", :size =>'620x400') unless @post.image.blank? %>
      </div>
      
      <div class="post-details">
        <div class="post-actions">
          <%= link_to add_post_path(@post), method: :post do %>
            <i class="fa fa-heart fa-2x post-like"></i>
          <% end %>
          <%= link_to post_path(@post) do %>
            <i class="fa fa-comment fa-2x post-comments"></i>
          <% end %>
        </div>
        <strong><%= @user.username %> </strong>
        <%= @post.description %>
        <p class="text-muted time-ago mt-3"><%= time_ago_in_words @post.created_at %>前に作成</p>
      </div>
      
      <div class="comment-box mb-5">
        <%= form_for [@post, @comment] do |f| %>
          <div class="form-group">
            <%= f.text_area :content, placeholder: "コメントを入力してください....", class: "form-control post-comment" %>
          </div>
          <div class="action text-center">
            <%= f.submit "コメントする", class: "btn btn-success" %>
          </div>
        <% end %>    
      </div>
    </div>
    
    <div class="col-md-4">
      <h2>コメント一覧</h2>
      <% @comments.each do |comment| %>
        <div class="comment mb-3">
          <%= image_tag(comment.user.image.thumb.url, class: "profile-pic") %>
          <strong class="ml-1 mr-1"><%= comment.user.username %></strong>
          <%= comment.content %>
       </div>
      <% end %>
    </div>
  </div>
</div>