config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#toppage"
  get "/search", :to => "users#search" 
  resources :rules, only: [:index]
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  } 
  devise_scope :user do
    get "users/sign_in", :to => "users/sessions#new"
    get "/users/sign_out", :to => "users/sessions#destroy" 
    get 'password_edit' => 'users/registrations#password_edit'
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :posts do 
    member do 
      post "add", to: "favorites#create"
    end
    resources :comments
  end
  
  resources :favorites, only: [:destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/layouts/_users_nav.html.erb
<div class="mt-1 mr-5">
  <%= form_tag(search_path, :method => "get") do %>
    <%= text_field_tag :search, '', placeholder: 'ユーザーを検索' %> 
    <%= submit_tag "検索" ,:username => nil %> 
  <% end %> 
</div>
<li class="nav-item">
  <%= link_to "トップ", posts_path, class: "nav-link" %>
</li>
<li class="nav-item">
  <%= link_to "ユーザー", users_path, class: "nav-link" %>
</li>
<li class="nav-item">
  <%= link_to "通知", notifications_path, class: "nav-link" %>
</li>
<li class="nav-item">
  <%= link_to "プロフィール", user_path(current_user.id), class: "nav-link" %>
 </li>
<li class="nav-item">
  <%= link_to "ログアウト", destroy_user_session_path , method: :delete ,class: "nav-link" %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= yield(:title) %> |Instagram</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    "application", media: "all" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="#">Instagram</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <%= render "layouts/users_nav" %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>  
    <% flash.each do |message_type, message| %>
      <div class="text-center alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
    <% if user_signed_in? %>
      <footer>
        <%= link_to "写真を投稿する", new_post_path %>
      </footer>
    <% end %>
  </body>
</html